"""Generate TS types + Zod response validators from the backend's checked-in schemas.

Run from the UI repository: python3 scripts/generate-contracts.py
No network or package installation is required. Commit generated output with schema changes.
"""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
backend = root.parent / 'MeT-Music_Backend/docs'
http = json.loads((backend / 'openapi.json').read_text())
ws = json.loads((backend / 'websocket.schema.json').read_text())
definitions = {**http['components']['schemas'], **ws['$defs']}


def ts(s):
    if '$ref' in s:
        return s['$ref'].split('/')[-1]
    for key in ('anyOf', 'oneOf'):
        if key in s:
            return '(' + ' | '.join(ts(x) for x in s[key]) + ')'
    if 'const' in s:
        return json.dumps(s['const'], ensure_ascii=False)
    if 'enum' in s:
        return '(' + ' | '.join(json.dumps(x) for x in s['enum']) + ')'
    kind = s.get('type')
    if kind == 'array':
        return f'Array<{ts(s["items"])}>'
    if kind == 'object':
        if isinstance(s.get('additionalProperties'), dict) and not s.get('properties'):
            return 'Record<string, ' + ts(s['additionalProperties']) + '>'
        required = s.get('required', [])
        return '{ ' + ' '.join(json.dumps(k) + (':' if k in required else '?:') + ts(v) + ';' for k,v in s.get('properties', {}).items()) + ' }'
    return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(kind, 'JsonValue')


def zod(s):
    if '$ref' in s:
        return s['$ref'].split('/')[-1] + 'Schema'
    for key in ('anyOf', 'oneOf'):
        if key in s:
            xs=[zod(x) for x in s[key]]
            return xs[0] if len(xs)==1 else 'z.union([' + ', '.join(xs) + '])'
    if 'const' in s:
        return 'z.literal(' + json.dumps(s['const']) + ')'
    if 'enum' in s:
        return 'z.union([' + ', '.join('z.literal('+json.dumps(x)+')' for x in s['enum']) + '])'
    kind = s.get('type')
    if kind == 'object':
        if isinstance(s.get('additionalProperties'), dict) and not s.get('properties'):
            return 'z.record(z.string(), '+zod(s['additionalProperties'])+')'
        required = s.get('required', [])
        return 'z.strictObject({ ' + ', '.join(json.dumps(k)+': '+zod(v)+('' if k in required else '.optional()') for k,v in s.get('properties',{}).items()) + ' })'
    if kind == 'array':
        return 'z.array(' + zod(s['items']) + ')'
    expr={'string':'z.string()','integer':'z.number().int()','number':'z.number()','boolean':'z.boolean()','null':'z.null()'}.get(kind,'JsonValueSchema')
    for key,method in [('minimum','min'),('maximum','max'),('minLength','min'),('maxLength','max')]:
        if key in s:expr+=f'.{method}({s[key]})'
    if 'pattern' in s:expr+='.regex(new RegExp('+json.dumps(s['pattern'])+'))'
    return expr

lines=['// Generated by scripts/generate-contracts.py. Edit backend schemas, then regenerate.', 'import { z } from "zod";', '', 'export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };', 'const JsonValueSchema: z.ZodType<JsonValue> = z.lazy(() => z.union([z.string(), z.number(), z.boolean(), z.null(), z.array(JsonValueSchema), z.record(z.string(), JsonValueSchema)]));']
for name,schema in sorted(definitions.items()):
    if name == 'JsonValue':continue
    lines.extend(['',f'export type {name} = {ts(schema)};',f'export const {name}Schema: z.ZodType<{name}> = z.lazy(() => {zod(schema)});'])
lines.extend(['','export const responseSchemas = {'])
for path, methods in http['paths'].items():
    if not path.startswith('/api/web'):continue
    operation=methods.get('get',{})
    schema=operation.get('responses',{}).get('200',{}).get('content',{}).get('application/json',{}).get('schema')
    if schema:lines.append(f'  {json.dumps(path[len("/api/web"):])}: {zod(schema)},')
lines.extend(['} as const;', 'export type ApiPath = keyof typeof responseSchemas;', 'export type ApiResponseFor<P extends ApiPath> = z.infer<(typeof responseSchemas)[P]>;', ''])
output = root / 'packages/core/src/api/contracts.ts'
content = '\n'.join(lines)
if '--check' in sys.argv:
    if not output.exists() or output.read_text() != content:
        raise SystemExit('Generated contracts are stale; run python3 scripts/generate-contracts.py')
else:
    output.write_text(content)
